//Backup quotes for if API fails
export const quotes = [
    { id: 1, text: "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO", author: "Steve Jobs" },
    { id: 2, text: "LIFE IS WHAT HAPPENS WHEN YOU ARE BUSY MAKING OTHER PLANS", author: "John Lennon" },
    { id: 3, text: "THE FUTURE BELONGS TO THOSE WHO BELIEVE IN THE BEAUTY OF THEIR DREAMS", author: "Eleanor Roosevelt" },
    { id: 4, text: "IT IS DURING OUR DARKEST MOMENTS THAT WE MUST FOCUS TO SEE THE LIGHT", author: "Aristotle" },
    { id: 5, text: "DO NOT GO WHERE THE PATH MAY LEAD GO INSTEAD WHERE THERE IS NO PATH AND LEAVE A TRAIL", author: "Ralph Waldo Emerson" },
    { id: 6, text: "IN THE MIDDLE OF DIFFICULTY LIES OPPORTUNITY", author: "Albert Einstein" },
    { id: 7, text: "SUCCESS IS NOT FINAL FAILURE IS NOT FATAL IT IS THE COURAGE TO CONTINUE THAT COUNTS", author: "Winston Churchill" },
    { id: 8, text: "BELIEVE YOU CAN AND YOU ARE HALFWAY THERE", author: "Theodore Roosevelt" },
    { id: 9, text: "HAPPINESS DEPENDS UPON OURSELVES", author: "Aristotle" },
    { id: 10, text: "TURN YOUR WOUNDS INTO WISDOM", author: "Oprah Winfrey" },
    { id: 11, text: "WHAT WE THINK WE BECOME", author: "Buddha" },
    { id: 12, text: "THE BEST WAY TO PREDICT THE FUTURE IS TO INVENT IT", author: "Alan Kay" },
    { id: 13, text: "YOU MISS ONE HUNDRED PERCENT OF THE SHOTS YOU DO NOT TAKE", author: "Wayne Gretzky" },
    { id: 14, text: "EVERYTHING YOU CAN IMAGINE IS REAL", author: "Pablo Picasso" },
    { id: 15, text: "THE JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP", author: "Lao Tzu" },
    { id: 16, text: "DO WHAT YOU CAN WITH WHAT YOU HAVE WHERE YOU ARE", author: "Theodore Roosevelt" },
    { id: 17, text: "ACT AS IF WHAT YOU DO MAKES A DIFFERENCE IT DOES", author: "William James" },
    { id: 18, text: "KEEP YOUR FACE ALWAYS TOWARD THE SUNSHINE AND SHADOWS WILL FALL BEHIND YOU", author: "Walt Whitman" },
    { id: 19, text: "THE SECRET OF GETTING AHEAD IS GETTING STARTED", author: "Mark Twain" },
    { id: 20, text: "EVERY STRIKE BRINGS ME CLOSER TO THE NEXT HOME RUN", author: "Babe Ruth" },
    { id: 21, text: "THE MIND IS EVERYTHING WHAT YOU THINK YOU BECOME", author: "Buddha" },
    { id: 22, text: "DO NOT LET WHAT YOU CANNOT DO INTERFERE WITH WHAT YOU CAN DO", author: "John Wooden" },
    { id: 23, text: "THE BEST REVENGE IS MASSIVE SUCCESS", author: "Frank Sinatra" },
    { id: 24, text: "IF YOU WANT TO LIFT YOURSELF UP LIFT UP SOMEONE ELSE", author: "Booker T. Washington" },
    { id: 25, text: "THE ONLY LIMIT TO OUR REALIZATION OF TOMORROW WILL BE OUR DOUBTS OF TODAY", author: "Franklin D. Roosevelt" },
    { id: 26, text: "CHANGE YOUR LIFE TODAY DO NOT GAMBLE ON THE FUTURE ACT NOW WITHOUT DELAY", author: "Simone de Beauvoir" },
    { id: 27, text: "THE PURPOSE OF OUR LIVES IS TO BE HAPPY", author: "Dalai Lama" },
    { id: 28, text: "YOU MUST BE THE CHANGE YOU WISH TO SEE IN THE WORLD", author: "Mahatma Gandhi" },
    { id: 29, text: "THE GREATEST GLORY IN LIVING LIES NOT IN NEVER FALLING BUT IN RISING EVERY TIME WE FALL", author: "Nelson Mandela" },
    { id: 30, text: "DO NOT COUNT THE DAYS MAKE THE DAYS COUNT", author: "Muhammad Ali" }

];
